apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: k8s-learnovate-net-tls
spec:
  secretName: k8s-learnovate-net
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: learnovate-academy.net
  dnsNames:
    - learnovate-academy.net
    - www.learnovate-academy.net
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - learnovate-academy.net
          - www.learnovate-academy.net